export const GET_WITHDRAWALS_SUCCESS = "GET_WITHDRAWALS_SUCCESS";
export const GET_WITHDRAWALS_FAIL = "GET_WITHDRAWALS_FAIL";
export const PAY_USER_SUCCESS = "PAY_USER_SUCCESS";
export const PAY_USER_FAIL = "PAY_USER_FAIL";
export const APPROVE_WITHDRAWAL_SUCCESS = "APPROVE_WITHDRAWAL_SUCCESS";
export const APPROVE_WITHDRAWAL_FAIL = "APPROVE_WITHDRAWAL_FAIL";
